name: Sync Docs to Wiki

on:
  push:
    paths:
      - 'docs/**'       # Triggers the workflow only if there are changes in the /docs folder

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Copy docs to Wiki directory
      run: |
        rm -rf wiki
        git clone "https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.wiki.git" wiki
        rsync -av --delete docs/ wiki/ # Syncs all files from /docs to the wiki directory

    - name: Configure Git author
      run: |
        cd wiki
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git config user.name "GitHub Actions Bot"

    - name: Commit and push changes
      run: |
        cd wiki
        git add .
        git commit -m "Update Wiki from /docs folder"
        git push origin main

