name: Sync Docs to Wiki

on:
  push:
    paths:
      - 'docs/**'       # Triggers the workflow only if there are changes in the /docs folder

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the main repository (into subfolder)
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        path: main_repo             # Checkout main repository in a subfolder
        fetch-depth: 0

    # Step 2: Check out the Wiki repository in a separate folder
    - name: Check out the Wiki repository
      uses: actions/checkout@v3
      with:
        repository: ${{ github.repository }}.wiki # Specifies the wiki repo
        token: ${{ secrets.GH_TOKEN }}            # Use the PAT to authenticate
        path: wiki_repo                           # Checkout the wiki repository to 'wiki_repo' folder

    # Step 3: Copy files from the /docs folder in main repository to wiki repository
    - name: Sync /docs folder to Wiki repository
      run: |
        rsync -av --delete --exclude='.git' main_repo/docs/ wiki_repo/  # Sync files from 'main_repo/docs/' to 'wiki_repo/'

    # Step 4: Setup git author and mail
    - name: Configure Git author
      run: |
        cd wiki_repo
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git config user.name "GitHub Actions Bot"

    # Step 5: Commit files and push the wiki repository
    - name: Commit and push changes
      run: |
        cd wiki_repo
        git add .
        git commit -m "Update Wiki from /docs folder"
        git push origin main

